/// Run this script from your project root:
///   dart run tool/generate_assets.dart

import 'dart:io';

void main() {
  // ✅ الفولدرات اللي هتتمشي عليها
  final assetFolders = [
    'assets/images',
    'assets/icons',
    'assets/json',
    'assets/pdfs',
    'assets/logos',
    'assets/png',
    'assets/fonts',
  ];

  // ✅ المكان اللي هيتحط فيه الفايل الناتج
  const outputPath = 'lib/res/assets.dart';

  final entries = <_AssetEntry>[];

  for (final folder in assetFolders) {
    final dir = Directory(folder);
    if (!dir.existsSync()) {
      print('⚠️  Folder not found, skipping: $folder');
      continue;
    }

    final files = dir
        .listSync()
        .whereType<File>()
        .toList()
      ..sort((a, b) => a.path.compareTo(b.path));

    for (final file in files) {
      final relativePath = file.path.replaceAll('\\', '/');
      final varName = _toVarName(relativePath);
      entries.add(_AssetEntry(varName, relativePath));
    }
  }

  // ✅ ابنِ محتوى الفايل
  final buffer = StringBuffer();
  buffer.writeln('///This file is automatically generated. DO NOT EDIT, all your changes would be lost.');
  buffer.writeln('class Assets {');
  buffer.writeln('  Assets._();');
  buffer.writeln();

  for (final entry in entries) {
    buffer.writeln("  static const String ${entry.name} = '${entry.path}';");
  }

  buffer.writeln('}');

  // ✅ اعمل الفولدر لو مش موجود واكتب الفايل
  final outputFile = File(outputPath);
  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync(buffer.toString());

  print('✅ Generated ${entries.length} assets → $outputPath');
}

// ---- helpers ----

class _AssetEntry {
  final String name;
  final String path;
  const _AssetEntry(this.name, this.path);
}

/// aboutMeImage.png   →  aboutMeImage  (already camelCase → keep as-is)
/// my_fun_facts.png   →  myFunFacts    (snake_case → camelCase)
/// Muhammad Essam.pdf →  muhammadEssam (spaces → camelCase)
String _toVarName(String filePath) {
  // خد اسم الفايل بدون الامتداد
  final fileName = filePath.split('/').last;
  final withoutExt = fileName.contains('.')
      ? fileName.substring(0, fileName.lastIndexOf('.'))
      : fileName;

  // نظّف: شيل أي حاجة غير حروف أو أرقام أو مسافات أو underscore أو hyphen
  final cleaned = withoutExt.replaceAll(RegExp(r'[^a-zA-Z0-9 _-]'), ' ').trim();

  // لو الاسم مفيش فيه separator (مسافة أو _ أو -)
  // ومفيش حاجة غير حروف وأرقام → خليه زي ما هو (camelCase أصلاً)
  final hasSeparator = cleaned.contains(RegExp(r'[\s_-]'));
  if (!hasSeparator) {
    // بس تأكد إن أول حرف lowercase
    return cleaned[0].toLowerCase() + cleaned.substring(1);
  }

  // قسّم على مسافات أو underscore أو hyphen وحوّل لـ camelCase
  final parts = cleaned.split(RegExp(r'[\s_-]+'));

  if (parts.isEmpty) return 'unknown';

  final result = StringBuffer(parts.first[0].toLowerCase() + parts.first.substring(1).toLowerCase());
  for (var i = 1; i < parts.length; i++) {
    if (parts[i].isEmpty) continue;
    result.write(parts[i][0].toUpperCase() + parts[i].substring(1).toLowerCase());
  }

  return result.toString();
}