def get_flutter_version
  project_root = sh("git rev-parse --show-toplevel").strip
  version_file = File.join(project_root, "pubspec.yaml")

  content = File.read(version_file)

  match = content.match(/version:\s(\d+)\.(\d+)\.(\d+)\+(\d+)/)
  raise "Version not found in pubspec.yaml" unless match

  major = match[1].to_i
  minor = match[2].to_i
  patch = match[3].to_i
  build = match[4].to_i

  current_version = "#{major}.#{minor}.#{patch}+#{build}"

  puts "📦 Current Flutter version: #{current_version}"

  return current_version
end


platform :android do

  lane :beta do

   new_version = get_flutter_version

    sh("flutter pub get")
    sh("flutter build apk --release --no-tree-shake-icons")



    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      testers: "muhammad159e@gmail.com",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      release_notes: "Build #{new_version} - #{Time.now.strftime('%Y-%m-%d %H:%M')}"
    )
  end
end