def increment_flutter_version(type)

  project_root = sh("git rev-parse --show-toplevel").strip
  version_file = File.join(project_root, "pubspec.yaml")

  content = File.read(version_file)

  match = content.match(/version:\s(\d+)\.(\d+)\.(\d+)\+(\d+)/)
  raise "Version not found in pubspec.yaml" unless match

  major = match[1].to_i
  minor = match[2].to_i
  patch = match[3].to_i
  build = match[4].to_i + 1

  case type
  when "major"
    major += 1
    minor = 0
    patch = 0
  when "minor"
    minor += 1
    patch = 0
  else
    patch += 1
  end

  new_version = "#{major}.#{minor}.#{patch}+#{build}"

  updated_content = content.sub(
    /version:\s\d+\.\d+\.\d+\+\d+/,
    "version: #{new_version}"
  )

  File.write(version_file, updated_content)

  puts "✅ pubspec.yaml updated to #{new_version}"

  return new_version
end


platform :android do

  lane :patch do
    increment_flutter_version("patch")
  end

  lane :minor do
    increment_flutter_version("minor")
  end

  lane :major do
    increment_flutter_version("major")
  end

  lane :beta do

   new_version = increment_flutter_version("patch")

    sh("flutter pub get")
    sh("flutter build apk --release --no-tree-shake-icons")

    add_git_tag(
      tag: "v#{new_version}"
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      testers: "muhammad159e@gmail.com",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      release_notes: "Build #{new_version} - #{Time.now.strftime('%Y-%m-%d %H:%M')}"
    )
  end
end